### ISSUE TITLE
On Readonly books fetching CORS error / 关于页面报错 CORS 问题

### ISSUE THREAD

**Issue by iscas-zac** [readonlylink/readonlylink-books#1]
I clicked the site book and it prints CORS error information in the console, and wondered if I misconfigured my browser.
> Access to fetch at 'https://books.readonly.link/caesar/commentarii-de-bello-gallico/book.json' from origin 'https://readonly.link' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 

今天发现上传的那些书，点开几本，发现出现了类似这样的问题，不知道是不是我的浏览器设置有缺陷，姑且放个 Issue 在这里。

PS. 早知道你这有了 K&R 的网页版本，我就不用放个 PDF 在 Kindle 里折磨自己了。不过看起来有些格式还是有问题，比如附录 B 好像就没有高亮二级标题？

**Comment by xieyuheng** [comment]
@iscas-zac 对不起这么晚才回复。我不知道为什么看不到 issue 和 PR 的提示。

关于上面说的那本拉丁语书，我是用 https://github.com/xieyuheng/x-server 来 serve 出来的。

你可以用任意的方式通过 HTTP 协议 serve 出来你的书，只要选择支持 CORS 就可以了。

关于 K&R，我是想整理一个我自己看的版本，但是编辑的工作还挺多的，所以有些页面没有排版好。

**Comment by xieyuheng** [comment]
@iscas-zac 也许我应该让 readonly.link 支持用户登陆 + 上传书 的功能，这样大家就不用自己 serve HTTP 了。

**Comment by iscas-zac** [comment]
之前说的不是我自己托管（还没想那么长远）而是你网页上的那几本书，当时点不开，浏览器报了个 CORS 错误，现在去点的时候已经没有了，应该已经修好了吧。
