### ISSUE TITLE
add foss-books here?

### ISSUE THREAD

**Issue by ghost** [readonlylink/readonlylink-books#2]
Hi @xieyuheng, @readonlylink; how are you?

Can I make a pr for foss-books here? books that have a public domain license on software development?

**Comment by xieyuheng** [comment]
@nichdemos Hi there.

Sorry for late replay.

You can do a PR, and I will merge your PR as soon as possible.

**Comment by ghost** [comment]
Hi @xieyuheng, thanks again!
