### ISSUE TITLE
Can I share this project with my developer friends? 

### ISSUE THREAD

**Issue by ghost** [readonlylink/readonlylink-books#3]
Hi @xieyuheng, @readonlylink, how are you?

Is there any image or trademark rights in this open source project that restrict the dissemination and promotion of this project?

***I await any response to this question.***

**Comment by xieyuheng** [comment]
@nichdemos Hi there :)

No, you can share this project as your wish,
and there is no trademark right about "readonly" and "readonly.link" or "readonlylink",
it is just a name and a domain name.

**Comment by ghost** [comment]
Hi @xieyuheng, thanks for comment here!
